version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Add assignees
    open-pull-requests-limit: 20
    assignees:
      - "lucasilverentand"
